
tasks:
    - name: Launch FarmData2
      init: npm install
      before: ./bin/fd2-up.gitpod.bash
      command:
        npm run build:fd2
        npm run build:examples
        npm run build:school

        installDB.bash
          