
tasks:
    - name: Launch FarmData2
      init: npm install
      before: sh ./bin/fd2-up.gitpod.bash
      command: ./bin/installDB.bash
    - name: launch FarmData
      command: npm run build:fd2
